//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetTimeSyncTools_winform.i18n {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messageTable_2052 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messageTable_2052() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetTimeSyncTools_winform.i18n.messageTable.2052", typeof(messageTable_2052).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 正在获取时钟 的本地化字符串。
        /// </summary>
        internal static string String_Connecting {
            get {
                return ResourceManager.GetString("String_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否删除服务器？ 的本地化字符串。
        /// </summary>
        internal static string String_DeleteConfirm {
            get {
                return ResourceManager.GetString("String_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在删除服务器 的本地化字符串。
        /// </summary>
        internal static string String_DeleteConfirmCaption {
            get {
                return ResourceManager.GetString("String_DeleteConfirmCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器之间的时间差距比较大，请谨慎选择时钟源同步！ 的本地化字符串。
        /// </summary>
        internal static string String_DiffBetweenServersTooLarge {
            get {
                return ResourceManager.GetString("String_DiffBetweenServersTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时钟更新失败。0x{0}（{1}） 的本地化字符串。
        /// </summary>
        internal static string String_Failed {
            get {
                return ResourceManager.GetString("String_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备就绪 的本地化字符串。
        /// </summary>
        internal static string String_GetReady {
            get {
                return ResourceManager.GetString("String_GetReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 建议更新本机时间。 的本地化字符串。
        /// </summary>
        internal static string String_NeedUpdate {
            get {
                return ResourceManager.GetString("String_NeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时钟设置失败！ 的本地化字符串。
        /// </summary>
        internal static string String_SetFailed {
            get {
                return ResourceManager.GetString("String_SetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时钟设置成功！ 的本地化字符串。
        /// </summary>
        internal static string String_SetSuccess {
            get {
                return ResourceManager.GetString("String_SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时钟获取成功 的本地化字符串。
        /// </summary>
        internal static string String_Successful {
            get {
                return ResourceManager.GetString("String_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态未知，请更新时钟源 的本地化字符串。
        /// </summary>
        internal static string String_Unknown {
            get {
                return ResourceManager.GetString("String_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时钟更新失败 的本地化字符串。
        /// </summary>
        internal static string String_UpdateFailed {
            get {
                return ResourceManager.GetString("String_UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时钟更新成功 的本地化字符串。
        /// </summary>
        internal static string String_UpdateSuccess {
            get {
                return ResourceManager.GetString("String_UpdateSuccess", resourceCulture);
            }
        }
    }
}
